FROM python:3.11-slim

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/code

COPY req_api.txt .
RUN pip install --no-cache-dir -r req_api.txt

# COPY src/ ./src/
# COPY app/ ./app/
# COPY models/ ./models/

EXPOSE 8000

CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
