FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir \
    mlflow==2.17.2 \
    psycopg2-binary==2.9.9 \
    SQLAlchemy==2.0.35
    
EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
